on:
  workflow_call:
    inputs:
      toolchain:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dopsi/gh-actions-c-test
      options: --user ci

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: |
          CC=${{ inputs.toolchain }} LD=${{ inputs.toolchain }} cmake -B build -S .
          VERBOSE=1 cmake --build build

  test:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: ghcr.io/dopsi/gh-actions-c-test
      options: --user ci

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: |
          CC=${{ inputs.toolchain }} LD=${{ inputs.toolchain }} cmake -B build -S . -Dgh_c_testing=ON
          VERBOSE=1 cmake --build build

      - name: Run
        run: |
          VERBOSE=1 cmake --build build -- test

  reproducibility:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: ghcr.io/dopsi/gh-actions-c-test
      options: --user ci --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: |
          CC=${{ inputs.toolchain }} LD=${{ inputs.toolchain }} reprotest -s . "cmake -B build -S . && cmake --build build" "build/src/gh-c build/lib/*/*.a"
